language: php

env:
  global:
    - secure: "Deo+29/vgqSFY7B9NF5sE/PZBD+nH6EKIgrVB1Wbk0L36LDsqEv04yHm58QS35kbJ/Ziub1LGu//REglxX6EwljRjDQuzgbjlrjCmCeEKXz4VbdyXlv9RwdcQkHp+MAhQ25do+Jv98kEpfmxMZ+cGISmn38ew274a29OmCuazCvNY0+5+vFyTMfJm3Y33N24YnmE+dIGfNx5hpxweE9bL195E7ykg+ZsHIYOdHr/sh/WySkZHsga3+ixlcI9M1cuc8EjOR2LEREkCYEpwNn+nJWlT5K2NfCBzWPQ35P7ND9Ca5BOR2ZNfcASn7uLIEcispN/OH/j/tr2K2h+eK1zJq59IgiWI21C+ttnR0TDmESFUY0/ozq9KhCERKT0URg8BXk8NyetyG7iFWHODLyHPTnRRHT7QLTKCgnfY0GJcm0DbV4O+i/UaWGHn2qR3nFPjQ4Wau2WngFpGD2j77peWGZI/xzL38BHFbLVzsKadvo9pcppowt63uA9rhRpf1D7NI4hzrI1Gr329aANBfXOEZtlRLOr0Uhr3uBSt0TnWNIISxb4MnrGA69FwNHcpqhmRiZeV7UGHgdQ6TKpnZ4sirPGc3/W3zBOzeAlLsYis6aUMvbp4qMTE3OAtnD+OFgpnHkgTLGwseky5XY2l8X1xjRVnlayMIIByvm0LLKB1ww="

cache:
  directories:
    - $HOME/.composer/cache
    - .build/phpunit

stages:
  - coverage
  - infection

jobs:
  include:
    - stage: Coverage

      php: 7.2

      env: WITH_LOWEST=true

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - mkdir -p .build/phpunit

      script:
        - xdebug-enable
        - vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --dump-xdebug-filter=.build/phpunit/xdebug-filter.php
        - vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml --prepend=.build/phpunit/xdebug-filter.php
        - xdebug-disable

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: Infection

      php: 7.3

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - mkdir -p .build/infection
        - xdebug-enable

      script:
        - vendor/bin/infection --ignore-msi-with-no-mutations --min-covered-msi=100 --min-msi=100

notifications:
  email: false
