# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - push
  - pull_request

name: CI

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build Docker image
        uses: ./.github/actions/php-7.2
        with:
          args: php -v

      - name: Validate composer.json and composer.lock
        uses: ./.github/actions/php-7.2
        with:
          args: composer validate --strict

      - name: Install dependencies with composer
        uses: ./.github/actions/php-7.2
        with:
          args: composer install

      - name: Run localheinz/composer-normalize
        uses: ./.github/actions/php-7.2
        with:
          args: composer normalize --dry-run

      - name: Run friendsofphp/php-cs-fixer
        uses: ./.github/actions/php-7.2
        with:
          args: vendor/bin/php-cs-fixer fix --diff --dry-run --using-cache=no --verbose
